name: Build 3sx Batocera/rpi4 package

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 3sx repo
        uses: actions/checkout@v4
      
      - name: Clone Batocera build system (full repo)
        run: |
          git clone https://github.com/batocera-linux/batocera.linux.git batocera.linux
          cd batocera.linux
          git fetch --all
          git checkout master
          git submodule update --init --recursive
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y util-linux clang curl nasm \
            libx11-dev libxext-dev libxrandr-dev libxrender-dev libxfixes-dev \
            libxi-dev libxcursor-dev libxinerama-dev libxss-dev \
            libwayland-dev libwayland-bin libxkbcommon-dev libdrm-dev libgbm-dev make g++ gcc patch
      
      - name: Move 3sx source + recipe to Batocera
        run: |
          mkdir -p batocera.linux/package/3sx
          rsync -ar --exclude .git --exclude batocera.linux --exclude .github ./ batocera.linux/package/3sx/
          cp tools/batocera/rpi4/3sx.mk batocera.linux/package/3sx/3sx.mk
          cp tools/batocera/rpi4/Config.in batocera.linux/package/3sx/Config.in
      
      - name: Register 3sx in batocera-system Config.in
        run: |
          grep -qxF 'source "package/3sx/Config.in"' batocera.linux/package/batocera/core/batocera-system/Config.in || \
            echo 'source "package/3sx/Config.in"' >> batocera.linux/package/batocera/core/batocera-system/Config.in

      
      - name: Build 3sx Batocera/rpi4 package
        run: |
          cd batocera.linux
          script -q -c "make bcm2711-pkg PKG=3sx"
      
      - name: Upload built Batocera 3sx package
        uses: actions/upload-artifact@v4
        with:
          name: 3sx-batocera-rpi4
          path: batocera.linux/output/packages/bcm2711/*

