name: Build 3sx Batocera/rpi4 package

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 3sx repo
        uses: actions/checkout@v4

      - name: Clone Batocera build system (full repo)
        run: |
          git clone https://github.com/batocera-linux/batocera.linux.git batocera.linux
          cd batocera.linux
          git fetch --all
          git checkout master
          git submodule update --init --recursive

      - name: Install minimal host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y util-linux rsync

      - name: Add 3sx package to Batocera overlay
        run: |
          set -euo pipefail
          mkdir -p batocera.linux/package/batocera/utils/3sx
          rsync -ar --exclude .git --exclude batocera.linux --exclude .github ./ batocera.linux/package/batocera/utils/3sx/
          cp tools/batocera/rpi4/3sx.mk batocera.linux/package/batocera/utils/3sx/3sx.mk
          cp tools/batocera/rpi4/Config.in batocera.linux/package/batocera/utils/3sx/Config.in

      - name: Register 3sx in root Config.in (BR2_EXTERNAL path)
        run: |
          set -euo pipefail
          cd batocera.linux
          # Remove any previously added wrong literal include (without BR2_EXTERNAL)
          sed -i '\|^source "package/batocera/utils/3sx/Config.in"$|d' Config.in
          # Add the correct include using Batocera's br2-external variable
          LINE='source "$BR2_EXTERNAL_BATOCERA_PATH/package/batocera/utils/3sx/Config.in"'
          if ! grep -qxF "$LINE" Config.in; then
            echo "$LINE" >> Config.in
          fi
          # Sanity checks
          test -f package/batocera/utils/3sx/Config.in
          test -f package/batocera/utils/3sx/3sx.mk
          tail -n 20 Config.in

      # Do NOT source from batocera-system/Config.in; not needed for pkg-only builds

      - name: Build 3sx for Raspberry Pi 4 (bcm2711)
        run: |
          cd batocera.linux
          script -q -c "make bcm2711-pkg PKG=3sx"
        timeout-minutes: 120

      - name: Verify build output
        run: |
          cd batocera.linux
          echo "Checking for 3sx build artifacts..."
          find output/bcm2711 -name "*3sx*" -type f || echo "No 3sx files found"
          find output/bcm2711 -name "*3sx*" -type d || echo "No 3sx directories found"

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: 3sx-batocera-rpi4
          path: |
            batocera.linux/output/bcm2711/build/3sx*/
            batocera.linux/output/bcm2711/target/usr/bin/3sx*
          if-no-files-found: warn
