name: Build 3sx Batocera/rpi4 package

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0. Ensure repository is checked out
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1. Clone Batocera build system
      - name: Clone Batocera build system
        run: |
          git clone https://github.com/batocera-linux/batocera.linux.git batocera.linux
          cd batocera.linux
          git submodule update --init --recursive

      # 2. Install util-linux for script utility
      - name: Install util-linux
        run: sudo apt-get update && sudo apt-get install -y util-linux

      # 3. Debug: list package files (remove this after successful run)
      - name: Debug - list package files for troubleshooting
        run: |
          ls -l tools/batocera/rpi4/
          ls -l tools/batocera/

      # 4. Copy 3sx package files into Batocera tree
      - name: Copy package files
        run: |
          mkdir -p batocera.linux/package/3sx
          cp tools/batocera/rpi4/Config.in batocera.linux/package/3sx/Config.in
          cp tools/batocera/rpi4/3sx.mk batocera.linux/package/3sx/Makefile
          cp tools/batocera/3sx.sh batocera.linux/package/3sx/3sx.sh

      # 5. Register your package so Batocera build system sees it
      - name: Register 3sx in Batocera package Config.in
        run: echo 'source "package/3sx/Config.in"' >> batocera.linux/package/Config.in

      # 6. Build the package for rpi4 (simulate TTY for Batocera buildroot)
      - name: Build 3sx package for Batocera rpi4
        run: |
          cd batocera.linux
          script -q -c "make bcm2711-pkg PKG=3sx"

      # 7. Upload the built output for download (adjust output path if needed)
      - name: Upload built Batocera 3sx package
        uses: actions/upload-artifact@v4
        with:
          name: 3sx-batocera-rpi4
          path: batocera.linux/output/packages/bcm2711/*
