name: Build 3sx for Batocera rpi4

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: batocera-linux/batocera.linux
          path: batocera.linux

      - uses: actions/checkout@v4
        with:
          repository: daouid/3sx
          path: 3sx

      - name: Copy 3sx into Batocera package
        run: cp -r 3sx batocera.linux/package/3sx

      - name: Build Batocera Docker image
        run: |
          cd batocera.linux
          make batocera-docker-image

      - name: Build 3sx package for rpi4 (bcm2711)
        run: |
          cd batocera.linux
          export BATOCERA_DOCKER_OPTIONS="-t"
          make bcm2711-pkg PKG=3sx

