name: Build 3sx Batocera/rpi4 package

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 3sx repo
        uses: actions/checkout@v4
      
      - name: Clone Batocera build system
        run: |
          git clone https://github.com/batocera-linux/batocera.linux.git batocera.linux
          cd batocera.linux
          git fetch --all
          git checkout master
          git submodule update --init --recursive
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y util-linux clang curl nasm \
            libx11-dev libxext-dev libxrandr-dev libxrender-dev libxfixes-dev \
            libxi-dev libxcursor-dev libxinerama-dev libxss-dev \
            libwayland-dev libwayland-bin libxkbcommon-dev libdrm-dev libgbm-dev \
            make g++ gcc patch rsync cpio unzip bc wget file
      
      - name: Move 3sx source and recipe to Batocera
        run: |
          mkdir -p batocera.linux/package/3sx
          rsync -ar --exclude .git --exclude batocera.linux --exclude .github ./ batocera.linux/package/3sx/
          cp tools/batocera/rpi4/3sx.mk batocera.linux/package/3sx/3sx.mk
          cp tools/batocera/rpi4/Config.in batocera.linux/package/3sx/Config.in
      
      - name: Register 3sx in root Config.in
        run: |
          cd batocera.linux
          if ! grep -qxF 'source "package/3sx/Config.in"' Config.in; then
            echo 'source "package/3sx/Config.in"' >> Config.in
          fi
      
      - name: Register 3sx in batocera-system Config.in
        run: |
          cd batocera.linux
          SYSTEM_CONFIG="package/batocera/core/batocera-system/Config.in"
          if [ -f "$SYSTEM_CONFIG" ]; then
            if ! grep -qxF 'source "package/3sx/Config.in"' "$SYSTEM_CONFIG"; then
              echo 'source "package/3sx/Config.in"' >> "$SYSTEM_CONFIG"
            fi
          else
            echo "Warning: $SYSTEM_CONFIG not found"
          fi
      
      - name: Configure bcm2711 build with 3sx enabled
        run: |
          cd batocera.linux
          # Load the default config
          make bcm2711-config-load
          # Enable 3sx package
          echo "BR2_PACKAGE_3SX=y" >> configs/batocera-bcm2711_defconfig
          # Apply the updated config non-interactively
          make bcm2711-config-load
      
      - name: Build 3sx package
        run: |
          cd batocera.linux
          # Build without TTY interaction
          make bcm2711-build PKG=3sx || make 3sx
        timeout-minutes: 120
        env:
          MAKEFLAGS: "-j$(nproc)"
      
      - name: Verify build output
        run: |
          cd batocera.linux
          echo "Checking build directories..."
          find output/bcm2711 -name "*3sx*" -type d || true
          find output/bcm2711 -name "*3sx*" -type f || true
          
          if [ -d "output/bcm2711/build" ]; then
            echo "Build directory contents:"
            ls -lah output/bcm2711/build/ | grep 3sx || echo "No 3sx build directory found"
          fi
      
      - name: Package 3sx binaries
        run: |
          cd batocera.linux
          mkdir -p ../3sx-package
          
          # Copy compiled binaries
          if [ -d "output/bcm2711/target/usr/bin" ]; then
            find output/bcm2711/target/usr/bin -name "*3sx*" -exec cp {} ../3sx-package/ \; 2>/dev/null || true
          fi
          
          # Copy build artifacts
          if [ -d "output/bcm2711/build" ]; then
            find output/bcm2711/build -path "*/3sx*/3sx" -o -path "*/3sx*/*.so*" | xargs -I {} cp {} ../3sx-package/ 2>/dev/null || true
          fi
          
          ls -lah ../3sx-package/
      
      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: 3sx-batocera-rpi4
          path: 3sx-package/
          if-no-files-found: warn
      
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            batocera.linux/output/bcm2711/build/3sx*/
            batocera.linux/output/bcm2711/build/build-time.log
          if-no-files-found: ignore
