name: Build (macOS)

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: macos-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Cache dependencies
            uses: actions/cache@v4
            with:
                path: third_party
                key: ${{ runner.os }}-deps-${{ hashFiles('build-deps.sh') }}

          - name: Install dependencies
            run: sh build-deps.sh

          - name: Build for macOS
            run: |
                set -o pipefail
                cmake -B build -DCMAKE_BUILD_TYPE=Release
                cmake --build build --parallel 2>&1 | tee build.log
            shell: bash

          - name: Upload build log
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: build-log
                path: build.log
