name: Build and Release

on:
  push:
    branches:
      - "main"

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.04
    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential make clang cmake ninja-build pkg-config zip autoconf automake libtool

      - name: Build dependencies from source
        run: |
          chmod +x build-deps.sh
          ./build-deps.sh

      - name: Configure and build with CMake
        run: |
          cmake -S . -B build -G "Ninja"
          cmake --build build

      - name: Package artifact
        run: |
          mkdir -p artifacts
          zip -j artifacts/sf33rd-linux.zip build/sf33rd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sf33rd-linux
          path: artifacts/sf33rd-linux.zip

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            git
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build dependencies from source
        run: |
          chmod +x build-deps.sh
          ./build-deps.sh

      - name: Configure and build with CMake
        run: |
          cmake -S . -B build -G "Ninja"
          cmake --build build

      - name: Package artifact
        run: |
          mkdir -p artifacts
          zip -j artifacts/sf33rd-windows.zip build/sf33rd.exe build/*.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sf33rd-windows
          path: artifacts/sf33rd-windows.zip

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install cmake ninja pkg-config zip

      - name: Build dependencies from source
        run: |
          chmod +x build-deps.sh
          ./build-deps.sh

      - name: Configure and build with CMake
        run: |
          cmake -S . -B build -G "Ninja"
          cmake --build build

      - name: Package artifact
        run: |
          mkdir -p artifacts
          zip -j artifacts/sf33rd-macos.zip build/sf33rd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sf33rd-macos
          path: artifacts/sf33rd-macos.zip

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    permissions:
      contents: write
    steps:
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Build ${{ steps.timestamp.outputs.timestamp }}"
          tag_name: "build-${{ steps.timestamp.outputs.timestamp }}"
          files: artifacts/*.zip
          body: |
            Automated build from main branch
            
            **Commit:** `${{ github.sha }}`
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Date:** ${{ steps.timestamp.outputs.timestamp }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
